permalink: /:categories/:year/:month/:day/:title/
url: "http://ckilimci.github.io"
full_name: "Caglar Kilimci"
first_name: "Better to"
last_name: "write down.."
blog_title: "Better to write down.."
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "blog"
copyright_year: "2016"
google_analytics_code: "UA-6120982-3"
aboutme: "I like to move it, move it."
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
